name: aprende_numeros_colores
version: 1.0.0+1
description: Aplicación educativa para aprender números y colores con audio.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5

flutter:
  uses-material-design: true
